CREATE TYPE "status_transaksi" AS ENUM (
  'DITERIMA',
  'DIPROSES',
  'DALAM_PENGIRIMAN',
  'SELESAI'
);

CREATE TABLE "transaksi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tanggal_transaksi" date,
  "pelanggan_id" int,
  "status" status_transaksi
);

CREATE TABLE "transaksi_detail" (
  "transaksi_id" int,
  "produk_id" int,
  "jumlah_beli" int
);

CREATE TABLE "produk" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar(200),
  "harga" int(11),
  "stok" int,
  "kategori_produk_id" int
);

CREATE TABLE "kategori_produk" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar(200)
);

CREATE TABLE "pelanggan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar(200),
  "no_hp" varchar(15),
  "alamat" text
);

COMMENT ON TABLE "transaksi" IS 'Table untuk bertransaksi';

COMMENT ON COLUMN "transaksi"."tanggal_transaksi" IS 'Tanggal Transaksi';

COMMENT ON COLUMN "transaksi"."pelanggan_id" IS 'ID Pelanggan berelasi dengan ID dari Table Pelanggan';

COMMENT ON COLUMN "transaksi"."status" IS 'Status transaksi: DITERIMA, DIPROSES, DALAM_PENGIRIMAN, SELESAI';

COMMENT ON TABLE "transaksi_detail" IS 'Table Detail Transaksi';

COMMENT ON COLUMN "transaksi_detail"."transaksi_id" IS 'ID Transaksi berelasi dengan ID dari Table Transaksi';

COMMENT ON COLUMN "transaksi_detail"."produk_id" IS 'ID Produk berelasi dengan ID dari Table Produk';

COMMENT ON COLUMN "transaksi_detail"."jumlah_beli" IS 'Banyaknya produk yang dibeli';

COMMENT ON TABLE "produk" IS 'Table untuk Data Produk';

COMMENT ON COLUMN "produk"."nama" IS 'Nama Produk';

COMMENT ON COLUMN "produk"."harga" IS 'Harga Produk';

COMMENT ON COLUMN "produk"."stok" IS 'Stok Produk';

COMMENT ON COLUMN "produk"."kategori_produk_id" IS 'ID Kategori Produk berelasi dengan id pada tabel kategori produk';

COMMENT ON TABLE "kategori_produk" IS 'Table untuk Kategori Produk';

COMMENT ON COLUMN "kategori_produk"."nama" IS 'Nama Kategori';

COMMENT ON TABLE "pelanggan" IS 'Table untuk Data Pelanggan';

COMMENT ON COLUMN "pelanggan"."nama" IS 'Nama Pelanggan';

COMMENT ON COLUMN "pelanggan"."no_hp" IS 'No HP';

COMMENT ON COLUMN "pelanggan"."alamat" IS 'Alamat';

ALTER TABLE "produk" ADD FOREIGN KEY ("kategori_produk_id") REFERENCES "kategori_produk" ("id");

ALTER TABLE "transaksi_detail" ADD FOREIGN KEY ("transaksi_id") REFERENCES "transaksi" ("id");

ALTER TABLE "transaksi_detail" ADD FOREIGN KEY ("produk_id") REFERENCES "produk" ("id");

ALTER TABLE "transaksi" ADD FOREIGN KEY ("pelanggan_id") REFERENCES "pelanggan" ("id");
